@echo off
setlocal

REM Create ANNEX and SHA256SUMS (requires certutil on Windows)
if not exist ANNEX mkdir ANNEX

REM List key artifacts (adjust as needed)
set PDF=DOCS\DOC00_TEMPLATE\main.pdf

if not exist %PDF% (
  echo Missing PDF: %PDF%
  exit /b 1
)

REM SHA256
certutil -hashfile %PDF% SHA256 > ANNEX\SHA256_MAINPDF.txt
type ANNEX\SHA256_MAINPDF.txt > ANNEX\SHA256SUMS.txt

REM Minimal ANNEX.md
echo # ANNEX > ANNEX\ANNEX.md
echo Generated by MAKE_RELEASE.cmd >> ANNEX\ANNEX.md
echo. >> ANNEX\ANNEX.md
echo ## Files >> ANNEX\ANNEX.md
echo - %PDF% >> ANNEX\ANNEX.md
echo - ANNEX\SHA256SUMS.txt >> ANNEX\ANNEX.md
echo - QA\QA_REPORT_*.json >> ANNEX\ANNEX.md

REM ZIP (PowerShell compress)
powershell -ExecutionPolicy Bypass -Command "Compress-Archive -Force -Path DOCS,STYLEKIT,TOOLS,CONTRACT,ANNEX,QA,DB,REGISTRY -DestinationPath RELEASEPACK_PROJECT_L_v0_1.zip"

echo ReleasePack created: RELEASEPACK_PROJECT_L_v0_1.zip
endlocal
